name: yacht
author: Eric Bailey
maintainer: eric@ericb.me
github: yurrriq/exercism
version: 1.2.0.0

dependencies:
- base

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: Yacht
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - yacht
    - hspec
