name: knapsack
version: 1.0.0.0
author: Eric Bailey
github: yurrriq/exercism

dependencies:
  - base

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-patterns
  - -Wincomplete-uni-patterns

library:
  exposed-modules: Knapsack
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - knapsack
      - hspec
