name: lens-person
version: 0.1.0.3
author: Eric Bailey
github: yurrriq/exercism

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

dependencies:
- base
- lens
- time

library:
  exposed-modules: Person
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - lens-person
    - hspec
