name: bowling
version: 1.2.0.7

author: Eric Bailey
github: yurrriq/exercism

dependencies:
  - base
  - data-fix
  - finite-typelits
  - recursion-schemes

language: GHC2021

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-patterns
  - -Wincomplete-uni-patterns

library:
  exposed-modules: Bowling
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - bowling
      - hspec
