(defproject xclojure "0.1.0"
  :description  "Exercism Exercises in Clojure"
  :url          "https://github.com/yurrriq/exercism/tree/clojure"
  :source-paths ["anagram"
                 "beer-song"
                 "binary"
                 "bob"
                 "etl"
                 "gigasecond"
                 "grade-school"
                 "grains"
                 "leap"
                 "meetup"
                 "nucleotide-count"
                 "phone-number"
                 "point-mutations"
                 ;; "prime-factors"
                 "rna-transcription"
                 "robot-name"
                 "roman-numerals"
                 "scrabble-score"
                 "space-age"
                 "triangle"
                 "word-count"]
  :test-paths   ["anagram"
                 "beer-song"
                 "binary"
                 "bob"
                 "etl"
                 "gigasecond"
                 "grade-school"
                 "grains"
                 "leap"
                 "meetup"
                 "nucleotide-count"
                 "phone-number"
                 "point-mutations"
                 ;; "prime-factors"
                 "rna-transcription"
                 "robot-name"
                 "roman-numerals"
                 "scrabble-score"
                 "space-age"
                 "triangle"
                 "word-count"]
  :dependencies [[org.clojure/clojure    "1.7.0"]
                 [org.clojure/core.typed "0.3.11"]])
