blank_lines_upper_bound = 2
combine_control_expr = false
comment_width = 80
format_code_in_doc_comments = true
format_strings = true
group_imports = "StdExternalCrate"
imports_granularity = "Module"
match_block_trailing_comma = true
max_width = 80
reorder_impl_items = true
space_after_colon = true
space_before_colon = false
struct_field_align_threshold = 20
use_try_shorthand = true
wrap_comments = true
