name: proverb
author: Eric Bailey
github: yurrriq/exercism
version: 1.1.0.2

dependencies:
- base

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: Proverb
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - proverb
    - hspec
