name: house
author: Eric Bailey
github: yurrriq/exercism
version: 0.1.0.3

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

dependencies:
- base
- pointless-fun

library:
  exposed-modules: House
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - house
    - hspec
