name: book-store
version: 1.0.0.0

author: Eric Bailey
github: yurrriq/exercism

dependencies:
  - base
  - finitary
  - finite-typelits
  - multiset
  - search-algorithms

language: GHC2021

library:
  exposed-modules: BookStore
  source-dirs: src

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-patterns
  - -Wincomplete-uni-patterns

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - book-store
      - hspec
