name: armstrong-numbers
author: Eric Bailey
github: yurrriq/exercism
version: 1.1.0.3

dependencies:
- base

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: ArmstrongNumbers
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - armstrong-numbers
    - hspec
