name: two-bucket
version: 1.0.0.0

author: Eric Bailey
github: yurrriq/exercism

dependencies:
  - base
  - finitary
  - finite-typelits
  - ghc-typelits-knownnat
  - search-algorithms

language: GHC2021

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-patterns
  - -Wincomplete-uni-patterns

library:
  exposed-modules: TwoBucket
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - two-bucket
      - hspec
