name: sgf-parsing
author: Eric Bailey
github: yurrriq/exercism
version: 1.2.0.5

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

dependencies:
- base
- containers
- text

library:
  exposed-modules: Sgf
  source-dirs: src
  dependencies:
  - trifecta

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - sgf-parsing
    - hspec
