name: saddle-points
author: Eric Bailey
github: yurrriq/exercism
version: 1.5.0.8

dependencies:
- array
- base

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: Matrix
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - saddle-points
    - hspec
