name: simple-cipher
version: 1.2.0.5

dependencies:
- base

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: Cipher
  source-dirs: src
  dependencies:
  - MonadRandom

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - simple-cipher
    - hspec
