name: minesweeper
author: Eric Bailey
github: yurrriq/exercism
version: 1.1.0.5

dependencies:
- base

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: Minesweeper
  source-dirs: src
  dependencies:
  - containers
  - lens
  - linear

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - minesweeper
    - hspec
