name: isbn-verifier
version: 2.7.0.9

dependencies:
- base


ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: IsbnVerifier
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - isbn-verifier
    - hspec
