name: isbn-verifier
version: 2.7.0.9

dependencies:
- base

default-extensions:
- TemplateHaskell

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: IsbnVerifier
  source-dirs: src
  dependencies:
  - lens
  - trifecta

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - isbn-verifier
    - hspec
