name: rail-fence-cipher
author: Eric Bailey
github: yurrriq/exercism
version: 1.1.0.4

dependencies:
- base

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: RailFenceCipher
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - rail-fence-cipher
    - hspec
