name: series
author: Eric Bailey
github: yurrriq/exercism
version: 1.0.0.4

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

dependencies:
- base

library:
  exposed-modules: Series
  source-dirs: src
  dependencies:
  - safe

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - series
    - hspec
