name: diamond
author: Eric Bailey
github: yurrriq/exercism
version: 1.1.0.6

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

dependencies:
- base
- text

library:
  exposed-modules: Diamond
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - diamond
    - hspec
    - QuickCheck
    - text
    - string-conversions
