name: linked-list
author: Eric Bailey
github: yurrriq/exercism
version: 0.1.0.3

dependencies:
- base

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: Deque
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - linked-list
    - hspec
