name: atbash-cipher
author: Eric Bailey
github: yurrriq/exercism
version: 1.2.0.7

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

dependencies:
- base

library:
  exposed-modules: Atbash
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - atbash-cipher
    - hspec
