name: sum-of-multiples
author: Eric Bailey
github: yurrriq/exercism
version: 1.5.0.10

dependencies:
- base

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: SumOfMultiples
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - sum-of-multiples
    - hspec
