name: affine-cipher
version: 1.0.0.0
author: Eric Bailey
github: yurrriq/exercism

dependencies:
  - base

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-patterns
  - -Wincomplete-uni-patterns

library:
  exposed-modules: Affine
  source-dirs: src
  dependencies:
    - extra
    - mod

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - affine-cipher
      - hspec
