name: poker
version: 1.1.0.2

author: Eric Bailey
maintainer: eric@ericb.me
github: yurrriq/exercism

dependencies:
  - base
  - containers
  - finitary
  - finite-typelits
  - refined
  - trifecta

language: GHC2021

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-patterns
  - -Wincomplete-uni-patterns

library:
  exposed-modules: Poker
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - poker
      - hspec
