name: rna-transcription
author: Eric Bailey
github: yurrriq/exercism
version: 1.3.0.10

dependencies:
- base

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: DNA
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - rna-transcription
    - hspec
