name: spiral-matrix
version: 1.1.0.3

author: Eric Bailey
github: yurrriq/exercism

dependencies:
  - base

language: GHC2021

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-patterns
  - -Wincomplete-uni-patterns

library:
  exposed-modules: Spiral
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - spiral-matrix
      - hspec
