name: dominoes
version: 2.1.0.9

author: Eric Bailey
github: yurrriq/exercism

dependencies:
  - base
  - refined

language: GHC2021

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-patterns
  - -Wincomplete-uni-patterns

library:
  exposed-modules: Dominoes
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - dominoes
      - hspec
