name: wordy
version: 1.5.0.8
author: Eric Bailey
github: yurrriq/exercism

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

dependencies:
- base

library:
  exposed-modules: WordProblem
  source-dirs: src
  dependencies:
  - parsers
  - trifecta

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - wordy
    - hspec
