name: pig-latin
author: Eric Bailey
github: yurrriq/exercism
version: 1.2.0.7

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

dependencies:
- base

library:
  exposed-modules: PigLatin
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - pig-latin
    - hspec
