name: bank-account
author: Eric Bailey
github: yurrriq/exercism
version: 0.1.0.4

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

dependencies:
- base
- deepseq
- stm

library:
  exposed-modules: BankAccount
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    ghc-options: -threaded -rtsopts -with-rtsopts=-N
    dependencies:
    - bank-account
    - hspec
