name: change
author: Eric Bailey
github: yurrriq/exercism
version: 1.3.0.7

dependencies:
- base

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: Change
  source-dirs: src
  dependencies:
  - groups

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - change
    - hspec
