name: word-count
version: 1.4.0.8

dependencies:
- base
- containers
- split

library:
  exposed-modules: WordCount
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - word-count
    - hspec
