name: sieve
author: Eric Bailey
github: yurrriq/exercism
version: 1.1.0.5

dependencies:
- base

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: Sieve
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - sieve
    - hspec
