name: game-of-life
version: 1.0.0.0

dependencies:
  - base

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-patterns
  - -Wincomplete-uni-patterns

library:
  exposed-modules: GameOfLife
  source-dirs: src
  dependencies:
    - containers
    - lens
    - linear

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - game-of-life
      - hspec
