name: state-of-tic-tac-toe
version: 1.0.0.0

dependencies:
  - base

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-patterns
  - -Wincomplete-uni-patterns

library:
  exposed-modules: StateOfTicTacToe
  source-dirs: src
  ghc-options: -Wall
  dependencies:
    - lens
    - trifecta

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - state-of-tic-tac-toe
      - hspec
