name: say
author: Eric Bailey
github: yurrriq/exercism
version: 1.2.0.6

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

dependencies:
- name: base
  mixin:
  - hiding (Prelude)
- name: relude
  mixin:
  - (Relude as Prelude)
  - ''

library:
  exposed-modules: Say
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - say
    - hspec
