name: transpose
author: Eric Bailey
github: yurrriq/exercism
version: 1.1.0.2

dependencies:
- base

flags:
  reddit:
    default: False
    description: Whether to try to follow the Reddit post instead
    manual: True

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: Transpose
  source-dirs: src
  when:
  - condition: flag(reddit)
    cpp-options: -DREDDIT

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - transpose
    - hspec
