name: grains
author: Eric Bailey
github: yurrriq/exercism
version: 1.2.0.6

dependencies:
- base

flags:
  recursive:
    default: False
    description: Whether to use a recursive algorithm
    manual: True

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: Grains
  source-dirs: src
  when:
  - condition: flag(recursive)
    cpp-options: -DRECURSIVE

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - grains
    - hspec
