name: custom-set
author: Eric Bailey
github: yurrriq/exercism
version: 1.3.0.6

dependencies:
- base

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: CustomSet
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - custom-set
    - hspec
