name: nucleotide-count
author: Eric Bailey
github: yurrriq/exercism
version: 1.3.0.8

dependencies:
- base
- containers

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: DNA
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - nucleotide-count
    - hspec
