name: isogram
author: Eric Bailey
github: yurrriq/exercism
version: 1.7.0.8


dependencies:
- base

ghc-options:
- -Wall
- -Werror
- -Wincomplete-patterns
- -Wincomplete-uni-patterns

library:
  exposed-modules: Isogram
  source-dirs: src
  dependencies:
  - containers

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
    - isogram
    - hspec
