name: alphametics
version: 1.3.0.6

author: Eric Bailey
github: yurrriq/exercism

dependencies:
  - base
  - containers
  - extra
  - fast-digits
  - trifecta

language: GHC2021

ghc-options:
  - -Wall
  - -Werror
  - -Wincomplete-patterns
  - -Wincomplete-uni-patterns

library:
  exposed-modules: Alphametics
  source-dirs: src

tests:
  test:
    main: Tests.hs
    source-dirs: test
    dependencies:
      - alphametics
      - hspec
